language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=4015795135868ee4781bd8cad1d345c20e7d0c2ef6ad5b0f08ccb13da24e66a1

stages:
  - test
  - deploy

go:
  - 1.13.x

sudo: required
dist: trusty

before_install:
  - go get -u golang.org/x/lint/golint
  - make deps
  - curl -L https://github.com/SimonBaeumer/commander/releases/download/v0.3.0/commander-linux-amd64 -o ~/bin/commander
  - chmod +x ~/bin/commander

jobs:
  include:
    - name: Unit tests
      script: make test

    - stage: deploy
      name: "Deployment"
      if: tag IS present
      script: make release
      deploy:
        provider: releases
        overwrite: true
        api_key:
          secure: amZy46LUflpI5nKCaqG05bAHAqLmcUXQkoTK450wp17a7wCrH54JVsQFsMfsEn2Cl41Pa1pZ7BBu1yAF/BjOg/M2tsnQT1f48sq5bPVfdnBwAjirGx0CIAtl9rV3oNH5G8kQJGDXJVV6tuElebJVgdJ5aq1+PHSzw0EaJdq27stvjtDSYq5eyQrKn7sa5C9gH92fuDS4zg10LR34MPSUUVPoC2qZl66Ft0zP5ym3Ilmes+mABj+cfjLt3X1z/+Kt0toqhE0eQnOYmu/B3r6Ph+9oKfUesFwkdpo+9xgNgQiEAYvTF79b6uhYNRPNxEyTINx5DJP6s8S3B9AvqgWu20Ly1pMo9q8XZZYrQgjzGCpMKmAZAi/6XfDPqgmDFJmPye23dnK1PtASdHWFKideDPopozovsVcBwWqSkZS+yV6UzTLJPo+XTh3z+h7SkbKoNbSeFQn0EObXc9nqhik5HbwCkqxkrlIGDl2qKtbPO4chWB8c0usXY/X2C5wydKZkoueH/Zu+79HWs4sO4czJ9SZC2hyU9cVcnDDVn3/N/ztrLK649puJlIc57zGCJ7iAEOnvf4ciiJh4/C+HaiePpkt2kyxYe0qc5XF42t39JnI29y/WpPq98I8kvpS545k2kUtQZSNGVPR/yrRI8WeBhSPtAuJcNEm+uGyDlkh+t+M=
        file:
          - release/monorepo-operator-linux-amd64
          - release/monorepo-operator-linux-arm
          - release/monorepo-operator-linux-386
          - release/monorepo-operator-mac-amd64
          - release/monorepo-operator-windows-amd64.exe
          - release/monorepo-operator-windows-386.exe
        skip_cleanup: true
        on:
          repo: SimonBaeumer/monorepo-operator
          tags: true