version: '3.7'

services:
  git-server:
    build: git
    ports:
      - "22"
      - "127.0.0.1:2222:22"
    networks:
      - git_net
    expose:
      - 22

  git-client:
    build: client
    user: "${UID}"
    volumes:
      - ./:/app
    networks:
      - git_net

networks:
  git_net:
    ipam:
      driver: default
      config:
      - subnet: "172.16.100.0/24"